# Generated by Django 5.2.5 on 2025-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tasks.task'),
        ),
    ]
